import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { CitedMarkdown } from "@/components/cited-markdown";
import { Jalur } from "@/components/jalur";
import { PrintButton } from "@/components/print-button";
import { Container, Pill } from "@/components/ui";
import { api, ApiError } from "@/lib/api";
import { catalog, jalurCells } from "@/lib/data";

// Rendered on first visit, then cached; refreshed at most every minute so review decisions show up quickly.
export const revalidate = 60;
export async function generateStaticParams() {
  return [];
}

export async function generateMetadata({ params }: PageProps<"/district/[slug]/brief">): Promise<Metadata> {
  const { slug } = await params;
  try {
    const p = await api.district(slug);
    return {
      title: `${p.district.name} district brief`,
      description: `A cited economic brief on ${p.district.name}, ${p.district.division} Division, Sabah: what the data shows, where the district stands among its peers, and the sources behind each claim.`,
      alternates: { canonical: `/district/${slug}/brief` },
    };
  } catch {
    return { title: "District brief" };
  }
}

export default async function BriefPage({ params }: PageProps<"/district/[slug]/brief">) {
  const { slug } = await params;
  let brief;
  try {
    brief = await api.brief(slug);
  } catch (e) {
    if (e instanceof ApiError && e.status === 404) notFound();
    throw e;
  }
  const [p, cat] = await Promise.all([api.district(slug), catalog()]);
  const reviewed = brief.status === "reviewed";

  return (
    <Container className="max-w-4xl py-8 print:py-0">
      <div className="no-print mb-4 flex flex-wrap items-center justify-between gap-2">
        <Link href={`/district/${slug}`} className="font-mono text-xs uppercase tracking-wider text-muted hover:text-laut">← {p.district.name} profile</Link>
        <PrintButton />
      </div>
      <article className="dastar p-6 print:border-0 print:p-0 print:shadow-none">
        <header className="border-b border-line pb-4">
          <p className="kicker">SabahKu · District brief · {p.district.division} Division</p>
          <h1 className="mt-1 font-display text-3xl font-semibold">{p.district.name}</h1>
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <Pill tone={reviewed ? "good" : "warn"}>{reviewed ? `Reviewed by ${brief.reviewer}` : "AI-generated · unreviewed draft"}</Pill>
            <span className="font-mono text-[0.62rem] text-muted">
              Data release {brief.release} · {brief.validation.citations_valid}/{brief.validation.citations_total} citations verified · {brief.model_version}
            </span>
          </div>
          <div className="mt-3"><Jalur cells={jalurCells(p.indicators, cat.indicators)} height={14} cellWidth={16} gap={1.5} title={`${p.district.name} signature`} /></div>
        </header>
        <div className="mt-2 text-[0.95rem]"><CitedMarkdown text={brief.body_md} citations={brief.citations} /></div>
        <footer className="mt-6 border-t border-line pt-3">
          <p className="kicker text-muted">Sources cited</p>
          <ol className="mt-1 space-y-1 text-xs">
            {brief.citations.map((c) => (
              <li key={c.id}>
                <span className="font-mono">[{c.id}]</span>{" "}
                {c.type === "document" ? <>{c.title}, {c.publisher}{c.page ? `, p. ${c.page}` : ""}. <span className="break-all text-muted">{c.url}</span></> : <>{c.label}{c.vintage ? ` (source updated ${c.vintage})` : ""}</>}
              </li>
            ))}
          </ol>
          <p className="source-note mt-3">Generated by the SabahKu AI Analyst from official DOSM statistics and the atlas models. Every factual sentence is cited; the validator removed {brief.validation.stripped.length} unsupported sentence(s). {reviewed ? "" : "This draft has not yet been reviewed by a person."}</p>
        </footer>
      </article>
    </Container>
  );
}
