"""District briefs: generated by the Analyst, stored as drafts, published after human review."""

from __future__ import annotations

import json
from datetime import UTC, datetime

from atlas_api import queries as q
from atlas_api.analyst.engine import ask
from atlas_api.analyst.llm import get_llm
from atlas_api.db import conn, fetch, fetch_one


def _release() -> str:
    r = q.release()
    return r["version"] if r else "dev"


def generate(district_id: str, force: bool = False) -> dict:
    d = q.resolve_district(district_id)
    if not d:
        raise ValueError(district_id)
    rel = _release()
    bid = f"brief:{d['id']}:{rel}"
    if not force and fetch_one("SELECT 1 FROM insight WHERE id=%s", (bid,)):
        return {"id": bid, "status": "exists"}
    llm = get_llm()
    a = ask("", district=d["name"], brief=True, llm=llm)
    with conn() as c:
        c.execute(
            """INSERT INTO insight (id, district_id, kind, body_md, citations, validation, status, model_version, release)
               VALUES (%s,%s,'brief',%s,%s,%s,'draft',%s,%s)
               ON CONFLICT (id) DO UPDATE SET body_md=EXCLUDED.body_md, citations=EXCLUDED.citations,
                 validation=EXCLUDED.validation, status='draft', reviewer=NULL, reviewed_at=NULL,
                 model_version=EXCLUDED.model_version, created_at=now()""",
            (
                bid,
                d["id"],
                a.text,
                json.dumps(a.citations, ensure_ascii=False),
                json.dumps(
                    {
                        **a.validation,
                        "tokens_in": a.tokens_in,
                        "tokens_out": a.tokens_out,
                        "latency_ms": a.latency_ms,
                        "tool_calls": a.tool_calls,
                    }
                ),
                a.model,
                rel,
            ),
        )
        c.commit()
    return {
        "id": bid,
        "status": "draft",
        "citation_validity": a.validation["citation_validity"],
        "stripped": len(a.validation["stripped"]),
    }


def generate_all(only: str | None = None, force: bool = False) -> list[dict]:
    targets = [only] if only else [d["id"] for d in q.districts("sabah") if d["kind"] == "district"]
    out = []
    for t in targets:
        try:
            out.append({"district": t, **generate(t, force=force)})
        except Exception as e:  # noqa: BLE001 — one failure must not stop the batch
            out.append({"district": t, "error": str(e)})
        print(out[-1])
    return out


def review(district: str, approve: bool, reviewer: str, note: str = "") -> dict:
    d = q.resolve_district(district)
    row = fetch_one(
        "SELECT id FROM insight WHERE district_id=%s AND kind='brief' ORDER BY created_at DESC LIMIT 1",
        (d["id"] if d else district,),
    )
    if not row:
        raise ValueError(f"no brief for {district}")
    with conn() as c:
        c.execute(
            "UPDATE insight SET status=%s, reviewer=%s, review_note=%s, reviewed_at=%s WHERE id=%s",
            ("reviewed" if approve else "rejected", reviewer, note, datetime.now(UTC), row["id"]),
        )
        c.commit()
    return {"id": row["id"], "status": "reviewed" if approve else "rejected"}


def list_briefs() -> list[dict]:
    return fetch("""SELECT DISTINCT ON (i.district_id) i.id, i.district_id, d.slug, d.display_name AS name,
                          d.division, i.status, i.reviewer, i.reviewed_at, i.created_at, i.model_version,
                          (i.validation->>'citation_validity')::float AS citation_validity
                   FROM insight i JOIN district d ON d.id=i.district_id
                   WHERE i.kind='brief' ORDER BY i.district_id, i.created_at DESC""")


def get_brief(key: str) -> dict | None:
    d = q.resolve_district(key)
    did = d["id"] if d else key
    return fetch_one(
        """SELECT i.*, d.slug, d.display_name AS name FROM insight i JOIN district d ON d.id=i.district_id
                        WHERE i.district_id=%s AND i.kind='brief' ORDER BY i.created_at DESC LIMIT 1""",
        (did,),
    )
